"""解析 onnxruntime_c_api.h，生成 OrtApi 虚函数表的有序函数名表（供纯 Go 绑定使用）。

为什么必须程序化生成：
OrtApi 是一张几百项的函数指针表，靠手写偏移量极易错位，错位会导致直接崩溃。
头文件里 struct OrtApi 内没有任何条件编译块，因此"按顺序出现即为偏移"是可靠的。
"""
import re
import sys

HEADER = sys.argv[1]
OUT = sys.argv[2]

src = open(HEADER, encoding="utf-8", errors="replace").read()

# 1) 去掉注释（避免注释里出现形如函数声明的文本）
src = re.sub(r"/\*.*?\*/", "", src, flags=re.S)
src = re.sub(r"//[^\n]*", "", src)

# 2) 取出 struct OrtApi 定义体
m = re.search(r"struct\s+OrtApi\s*\{(.*?)\n\};", src, flags=re.S)
if not m:
    sys.exit("未找到 struct OrtApi 定义")

body = m.group(1)
# 确认结构体内没有条件编译，否则"顺序即偏移"不成立
cond = [l for l in body.splitlines() if l.strip().startswith("#")]
if cond:
    sys.exit("struct OrtApi 内存在条件编译，需人工处理：%s" % cond[:3])

names = []
unknown = []
for decl in body.split(";"):
    d = " ".join(decl.split())
    if not d:
        continue
    # ORT_CLASS_RELEASE(X) -> void(ORT_API_CALL * ReleaseX)(...)
    mm = re.search(r"ORT_CLASS_RELEASE\(\s*(\w+)\s*\)", d)
    if mm:
        names.append("Release" + mm.group(1))
        continue
    # ORT_API2_STATUS(NAME, ...) / ORT_API_STATUS(NAME, ...) / ORT_API(RET, NAME, ...)
    mm = re.search(r"ORT_API2?_STATUS\(\s*(\w+)\s*,", d)
    if mm:
        names.append(mm.group(1))
        continue
    mm = re.search(r"ORT_API\(\s*\w[\w\s\*]*?,\s*(\w+)\s*,", d)
    if mm:
        names.append(mm.group(1))
        continue
    # 常规成员：RetType (ORT_API_CALL * Name)(args)
    mm = re.search(r"\(ORT_API_CALL\s*\*\s*(\w+)\s*\)\s*\(", d)
    if mm:
        names.append(mm.group(1))
        continue
    mm = re.search(r"\(\s*\*\s*(\w+)\s*\)\s*\(", d)
    if mm:
        names.append(mm.group(1))
        continue
    unknown.append(d[:120])

print("解析到 OrtApi 函数项: %d 个" % len(names))
# 任何无法识别的成员都会让后续所有偏移整体错位，必须视为致命错误
if unknown:
    print("未能识别的声明 (%d):" % len(unknown))
    for u in unknown[:20]:
        print("   ?", u)
    sys.exit("存在无法识别的 struct OrtApi 成员，偏移表不可信，已中止")

# 3) 校验我们需要的函数都存在
REQUIRED = [
    "GetErrorMessage", "CreateEnv", "ReleaseEnv", "CreateSessionOptions",
    "ReleaseSessionOptions", "SetIntraOpNumThreads", "SetInterOpNumThreads",
    "SetSessionGraphOptimizationLevel", "CreateSession", "ReleaseSession",
    "GetAllocatorWithDefaultOptions", "AllocatorFree", "SessionGetInputName",
    "SessionGetOutputName", "SessionGetInputTypeInfo", "SessionGetOutputTypeInfo",
    "CastTypeInfoToTensorInfo", "GetDimensionsCount", "GetDimensions",
    "ReleaseTypeInfo", "CreateCpuMemoryInfo", "ReleaseMemoryInfo",
    "CreateTensorWithDataAsOrtValue", "ReleaseValue", "Run",
    "GetTensorMutableData", "GetTypeInfo", "GetTensorShapeElementCount",
    "ReleaseStatus",
]
missing = [r for r in REQUIRED if r not in names]
if missing:
    sys.exit("缺少必需函数: %s" % missing)
print("必需函数校验通过 (%d/%d)" % (len(REQUIRED), len(REQUIRED)))

with open(OUT, "w", encoding="utf-8", newline="\n") as f:
    f.write("// Code generated by _gen_ort_table.py. DO NOT EDIT.\n")
    f.write("// 来源: third_party/onnxruntime-win-x64-1.19.2/include/onnxruntime_c_api.h\n")
    f.write("// OrtApi 虚函数表按声明顺序展开，下标即为函数指针偏移（64 位下每项 8 字节）。\n\n")
    f.write("package infer\n\n")
    f.write("// ortApiFuncNames 为 OrtApi 虚函数表的有序函数名列表，下标 = vtable 偏移。\n")
    f.write("var ortApiFuncNames = []string{\n")
    for n in names:
        f.write("\t\"%s\",\n" % n)
    f.write("}\n")

print("已生成: %s" % OUT)
for r in REQUIRED:
    print("  %3d  %s" % (names.index(r), r))
